/*
 * This source file was generated by the Gradle 'init' task
 */
package interview.problems.solved;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void appHasAGreeting() {
        TrappingRainWater classUnderTest = new TrappingRainWater();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
